### ISSUE TITLE
OpenSSL error, fresh host/new install

### ISSUE THREAD

**Issue by nfguide** [VirtuBox/nginx-ee#93]
**Attach the following commands output**

- [ ] lsb_release -a : 
root@d9-host:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
root@d9-host:~#

- [ ] nginx -V : 
root@d9-host:~# nginx -V
-bash: nginx: command not found
root@d9-host:~#

**Describe the bug**

2020-05-01 19:38:49 (24.0 MB/s) - written to stdout [43301/43301]

Welcome to the nginx-ee bash script v3.6.5
Do you want to compile the latest Nginx [1] Mainline v1.17.10 or [2] Stable v Release ?
Select an option [1-2]:
1
Do you want Ngx_Pagespeed ? (y/n)
Select an option [y/n]:
n
Do you prefer to compile Nginx with OpenSSL [1] or LibreSSL [2] ? (y/n)
  [1] OpenSSL
  [2] LibreSSL
Select an option [1-2]:
1
What OpenSSL release do you want ?
  [1] OpenSSL stable 1.1.1d
  [2] OpenSSL dev 3.0.0-dev
  [3] OpenSSL from system lib
Select an option [1-2-3]:
3
Do you want NAXSI WAF (still experimental)? (y/n)
Select an option [y/n]:
n
Do you want RTMP streaming module (used for video streaming) ? (y/n)
Select an option [y/n]:
y
Do you want to build modules as dynamic modules? (y/n)
Select an option [y/n]:
y
Do you want to setup nginx-ee auto-update cronjob ? (y/n)
Select an option [y/n]:
y

##################################
 Compilation summary
##################################
 Detected OS : Debian GNU/Linux 9.12 (stretch)
 Detected Arch : x86_64
  - Nginx release : 1.17.10
  - OPENSSL : from system
  - Dynamic modules YES
  - Pagespeed : NO
  - Naxsi : NO
  - RTMP : YES
        Installing dependencies              [FAIL]
      Please look at /tmp/nginx-ee.log
root@d9-host:~# cat /tmp/nginx-ee.log

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Reading package lists...
Building dependency tree...
Reading state information...
libbz2-1.0 is already the newest version (1.0.6-8.1).
gnupg is already the newest version (2.1.18-8~deb9u4).
perl is already the newest version (5.24.1-3+deb9u6).
tar is already the newest version (1.29b-1.1).
git is already the newest version (1:2.11.0-3+deb9u7).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1d-1ppa~stable) but 1.1.0l-1~deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.

Same issue occurs when selecting OpenSSL option 1.  This is a fresh VPS install of Debian 9, nothing else on the host.

Thoughts?

**Comment by nfguide** [comment]
Issue occurs when selecting --dynamic.  Completed correctly when using --static.  What gives?

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please try again to run the script and it should work properly.

**Comment by nfguide** [comment]
Error still occurs.  Interactive script

root@d9-host:~# bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --interactive
--2020-05-02 18:14:03--  http://vtb.cx/nginx-ee
Resolving vtb.cx (vtb.cx)... 195.201.121.32, 2a01:4f8:1c1c:12f::1
Connecting to vtb.cx (vtb.cx)|195.201.121.32|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vtb.cx/nginx-ee [following]
--2020-05-02 18:14:03--  https://vtb.cx/nginx-ee
Connecting to vtb.cx (vtb.cx)|195.201.121.32|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh [following]
--2020-05-02 18:14:04--  https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43315 (42K) [text/plain]
Saving to: 'STDOUT'

-                                                             100%[===============================================================================================================================================>]  42.30K  --.-KB/s    in 0.002s

2020-05-02 18:14:04 (22.2 MB/s) - written to stdout [43315/43315]


Welcome to the nginx-ee bash script v3.6.6

Do you want to compile the latest Nginx [1] Mainline v1.17.10 or [2] Stable v1.18.0 Release ?
Select an option [1-2]:
1

Do you want Ngx_Pagespeed ? (y/n)
Select an option [y/n]:
n

Do you prefer to compile Nginx with OpenSSL [1] or LibreSSL [2] ? (y/n)
  [1] OpenSSL
  [2] LibreSSL

Select an option [1-2]:
1

What OpenSSL release do you want ?

  [1] OpenSSL stable 1.1.1g

  [2] OpenSSL dev 3.0.0-dev

  [3] OpenSSL from system lib

Select an option [1-2-3]:
1

Do you want NAXSI WAF (still experimental)? (y/n)
Select an option [y/n]:
n

Do you want RTMP streaming module (used for video streaming) ? (y/n)
Select an option [y/n]:
y

Do you want to build modules as dynamic modules? (y/n)
Select an option [y/n]:
y

Do you want to setup nginx-ee auto-update cronjob ? (y/n)
Select an option [y/n]:
y


##################################
 Compilation summary
##################################

 Detected OS : Debian GNU/Linux 9.12 (stretch)
 Detected Arch : x86_64

  - Nginx release : 1.17.10
  - OPENSSL : 1.1.1g Stable
  - Dynamic modules YES
  - Pagespeed : NO
  - Naxsi : NO
  - RTMP : YES

        Installing dependencies              [FAIL]

      Please look at /tmp/nginx-ee.log

root@d9-01nyc-livstrm:~# cat /tmp/nginx-ee.log

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Reading package lists...
Building dependency tree...
Reading state information...
libbz2-1.0 is already the newest version (1.0.6-8.1).
gnupg is already the newest version (2.1.18-8~deb9u4).
perl is already the newest version (5.24.1-3+deb9u6).
tar is already the newest version (1.29b-1.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1g-1~stable) but 1.1.0l-1~deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@d9-host:~#

**Comment by VirtuBox** [comment]
Hello @nfguide,
please try to run `apt-get update && apt-get dist-upgrade -y` to make sure there is no issue with old packages before running again the script.

**Comment by nfguide** [comment]
Will start with a fresh deb 9 install.

Will run apt update && apt dist-upgrade -y

Will run interactive install, with Openssl 1.1, RTMP, and Dynamic selected.  Update to follow.

**Comment by nfguide** [comment]
Below is the output from fresh debian 9 install, one package added which was lsb, ran apt update and apt dist-upgrade.  Then ran lsb_release -a, and then the script as noted above.  Same error as originally reported.

root@d9-host:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
root@d9-host:~# bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --interactive
--2020-05-04 20:59:02--  http://vtb.cx/nginx-ee
Resolving vtb.cx (vtb.cx)... 195.201.121.32, 2a01:4f8:1c1c:12f::1
Connecting to vtb.cx (vtb.cx)|195.201.121.32|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vtb.cx/nginx-ee [following]
--2020-05-04 20:59:02--  https://vtb.cx/nginx-ee
Connecting to vtb.cx (vtb.cx)|195.201.121.32|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh [following]
--2020-05-04 20:59:03--  https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43315 (42K) [text/plain]
Saving to: 'STDOUT'

-                                                             100%[===============================================================================================================================================>]  42.30K  --.-KB/s    in 0.002s

2020-05-04 20:59:03 (22.0 MB/s) - written to stdout [43315/43315]


Welcome to the nginx-ee bash script v3.6.6

Do you want to compile the latest Nginx [1] Mainline v1.17.10 or [2] Stable v1.18.0 Release ?
Select an option [1-2]:
1

Do you want Ngx_Pagespeed ? (y/n)
Select an option [y/n]:
n

Do you prefer to compile Nginx with OpenSSL [1] or LibreSSL [2] ? (y/n)
  [1] OpenSSL
  [2] LibreSSL

Select an option [1-2]:
1

What OpenSSL release do you want ?

  [1] OpenSSL stable 1.1.1g

  [2] OpenSSL dev 3.0.0-dev

  [3] OpenSSL from system lib

Select an option [1-2-3]:
1

Do you want NAXSI WAF (still experimental)? (y/n)
Select an option [y/n]:
n

Do you want RTMP streaming module (used for video streaming) ? (y/n)
Select an option [y/n]:
y

Do you want to build modules as dynamic modules? (y/n)
Select an option [y/n]:
y

Do you want to setup nginx-ee auto-update cronjob ? (y/n)
Select an option [y/n]:
y


##################################
 Compilation summary
##################################

 Detected OS : Debian GNU/Linux 9.12 (stretch)
 Detected Arch : x86_64

  - Nginx release : 1.17.10
  - OPENSSL : 1.1.1g Stable
  - Dynamic modules YES
  - Pagespeed : NO
  - Naxsi : NO
  - RTMP : YES

        Installing dependencies              [FAIL]

      Please look at /tmp/nginx-ee.log

root@d9-host:~# cat /tmp/nginx-ee.log

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Reading package lists...
Building dependency tree...
Reading state information...
libbz2-1.0 is already the newest version (1.0.6-8.1).
gnupg is already the newest version (2.1.18-8~deb9u4).
perl is already the newest version (5.24.1-3+deb9u6).
tar is already the newest version (1.29b-1.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1g-1~stable) but 1.1.0l-1~deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@d9-host:~#

**Comment by VirtuBox** [comment]
Hello @nfguide, 
I will investigate on this, but I haven't be able to reproduce this issue on a fresh debian 9 install.

**Comment by nfguide** [comment]
Contact me if you want/need access to the host in use above.

**Comment by edisoncosta** [comment]
Hello @VirtuBox 

Error line 588 and 594 "strech" install repository debian_10, correct "stretch"
